<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net$(_MauiDotNetVersion)-maccatalyst</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>ResourcesProviderApplicationRetentionLeakRepro</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>ResourcesProviderApplicationRetentionLeakRepro</ApplicationTitle>
    <ApplicationId>com.microsoft.maui.resourcesproviderapplicationretentionleakrepro</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CS0612;CS0618;CA1416</NoWarn>
  </PropertyGroup>

  <Import Project="$(MauiSrcDirectory)Maui.InTree.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\src\Core.csproj" />
    <ProjectReference Include="..\..\..\Controls\src\Xaml\Controls.Xaml.csproj" />
    <ProjectReference Include="..\..\..\Controls\src\Core\Controls.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MauiIcon Include="..\Controls.Sample.Profiling\Resources\AppIcons\appicon.svg" ForegroundFile="..\Controls.Sample.Profiling\Resources\AppIcons\appicon_foreground.svg" Color="#455A64" />
    <MauiSplashScreen Include="..\Controls.Sample.Profiling\Resources\AppIcons\appicon_foreground.svg" Color="#455A64" BaseSize="128,128" />
  </ItemGroup>

</Project>
