<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks Condition="'$(IncludeAndroidTargetFrameworks)' == 'true'">net$(_MauiDotNetVersion)-android</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <SingleProject>true</SingleProject>
    <ApplicationTitle>AndroidViewHandlerBackgroundImageRetentionRepro</ApplicationTitle>
    <ApplicationId>com.microsoft.maui.androidviewhandlerbackgroundimageretentionrepro</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);XC0022</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition=" '$(UseMaui)' != 'true' ">
    <ProjectReference Include="..\..\..\Core\src\Core.csproj" />
    <ProjectReference Include="..\..\src\Xaml\Controls.Xaml.csproj" />
    <ProjectReference Include="..\..\src\Core\Controls.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MauiIcon Include="..\Controls.Sample.Profiling\Resources\AppIcons\appicon.svg" ForegroundFile="..\Controls.Sample.Profiling\Resources\AppIcons\appicon_foreground.svg" Color="#00695C" />
    <MauiSplashScreen Include="..\Controls.Sample.Profiling\Resources\AppIcons\appicon_foreground.svg" Color="#00695C" BaseSize="128,128" />
  </ItemGroup>

  <Import Project="$(MauiSrcDirectory)Maui.InTree.props" Condition=" '$(UseMaui)' != 'true' " />

</Project>
