<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks Condition="'$(IncludeAndroidTargetFrameworks)' == 'true'">net$(_MauiDotNetVersion)-android;$(TargetFrameworks)</TargetFrameworks>
    <TargetFrameworks Condition="'$(IncludeIosTargetFrameworks)' == 'true'">net$(_MauiDotNetVersion)-ios;$(TargetFrameworks)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <SingleProject>true</SingleProject>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationTitle>TabbedPage BarBackground Leak</ApplicationTitle>
    <ApplicationId>com.microsoft.maui.repros.tabbedpagebarbackgroundleak</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <EmbedAssembliesIntoApk Condition="$(TargetFramework.Contains('-android'))">true</EmbedAssembliesIntoApk>
    <_FastDeploymentDiagnosticLogging Condition="$(TargetFramework.Contains('-android'))">True</_FastDeploymentDiagnosticLogging>
  </PropertyGroup>

  <ItemGroup Condition=" '$(UseMaui)' != 'true' ">
    <ProjectReference Include="..\..\..\Core\src\Core.csproj" />
    <ProjectReference Include="..\..\..\Controls\src\Xaml\Controls.Xaml.csproj" />
    <ProjectReference Include="..\..\..\Controls\src\Core\Controls.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#00695c" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#00695c" BaseSize="128,128" />
  </ItemGroup>

  <Import Project="$(MauiSrcDirectory)Maui.InTree.props" Condition=" '$(UseMaui)' != 'true' " />

</Project>
