<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net$(_MauiDotNetVersion)-ios</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>CarouselViewDetachedRefreshRepro</RootNamespace>
    <AssemblyName>CarouselViewDetachedRefreshRepro</AssemblyName>
    <SingleProject>true</SingleProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <ApplicationTitle>Carousel Refresh Repro</ApplicationTitle>
    <ApplicationId>com.adamessenmacher.maui.carouselrefreshrepro</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup Condition=" '$(UseMaui)' != 'true' ">
    <ProjectReference Include="..\..\..\Core\src\Core.csproj" />
    <ProjectReference Include="..\..\src\Xaml\Controls.Xaml.csproj" />
    <ProjectReference Include="..\..\src\Core\Controls.Core.csproj" />
    <ProjectReference Include="..\..\..\Essentials\src\Essentials.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcons\appicon.svg" ForegroundFile="Resources\AppIcons\appiconfg.svg" Color="#203864" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#203864" BaseSize="128,128" />
  </ItemGroup>

  <Import Project="$(MauiSrcDirectory)Maui.InTree.props" Condition=" '$(UseMaui)' != 'true' " />

</Project>
