<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net$(_MauiDotNetVersion)</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <UseMaui>false</UseMaui>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\src\Core.csproj" />
    <ProjectReference Include="..\..\src\Xaml\Controls.Xaml.csproj" />
  </ItemGroup>

</Project>
